# Generated by Django 4.0.3 on 2022-03-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records_manager', '0002_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
