# Generated by Django 4.0.3 on 2022-03-25 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records_manager', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kid_meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('food_group', models.CharField(max_length=50)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records_manager.child')),
            ],
            options={
                'db_table': 'kid_meal',
            },
        ),
    ]
