# Generated by Django 4.0.3 on 2022-03-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_manager', '0005_kid_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent_contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
