# Generated by Django 4.0.3 on 2022-03-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records_manager', '0006_alter_child_parent_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid_meal',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
